// <auto-generated />
namespace Democracy1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _28112018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_28112018));
        
        string IMigrationMetadata.Id
        {
            get { return "201811281907246_28112018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
